### ISSUE TITLE
Messenger Cell

### ISSUE THREAD

**Issue by aemever** [skensell/MXRMessenger#15]
Please clarify how to implement a custom cell, or provide a way to create a custom cell (btw this is a great feature)

**Comment by hilalalhakani** [comment]
in NodeBlockForRow 

implement an ASCellNode 
and use  ASAbsoluteLayoutSpec 
it worked for me

I added an audio cell and video and image Cell

**Comment by skensell** [comment]
Yup, since the ViewController publicly implements the ASTable protocols, you can just return whatever cell you want for certain index paths.

**Comment by mikegunning** [comment]
@hilalalhakani can you include your audio and video implementation in a pull request?
