### ISSUE TITLE
Hide avatar from same author

### ISSUE THREAD

**Issue by brurend** [skensell/MXRMessenger#9]
I been trying to implement something similar to how facebook messenger works, if you receive multiple messages from the same person in a row its avatar only appears in the last message.

It should work similar to how the bubbles arrange themselves in the same case, and I did get it working when loading old messages but I couldn't get to update the cells when a new message is received.

Is there any way I could achieve that?

**Comment by CavalcanteLeo** [comment]
anyone? I need this help too!

**Comment by skensell** [comment]
Ah, interesting feature request!  I'll think about it.  Somehow I missed the email notification about this.

**Comment by skensell** [comment]
Here's the quick hack I came up with: https://github.com/skensell/MXRMessenger/pull/10

I need to test it more, and maybe you guys could try it out too. If it seems to be working I may merge it into master. For now you can use it by pointing your Podfile to that branch, with 
```Ruby
pod 'MXRMessenger', :git => 'https://github.com/skensell/MXRMessenger.git', :branch => 'less-avatars'
```

**Comment by brurend** [comment]
I tested here and its working great, thank you :)

btw, just to let you know, I'm working in sending/receiving audio as well. It will probably still take sometime, but I will open an PR when I'm done with it

**Comment by skensell** [comment]
I tested it a little too and it's working fine for me.  I merged that branch into master and am releasing a new version as 0.2.1.  So now you can update podfiles to 0.2.1.

About the sending/receiving audio -> That sounds awesome :)  You will earn a special badge as "First Contributor" 🎖
